/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Cards: () => import('#controllers/cards_controller'),
  Collections: () => import('#controllers/collections_controller'),
  Me: () => import('#controllers/me_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Session: () => import('#controllers/session_controller'),
  Sets: () => import('#controllers/sets_controller'),
  Syncs: () => import('#controllers/syncs_controller'),
}
